#!/usr/bin/env python3
"""
Lie Algebra Dimension as Order Parameter for Trainability

Computes dim(g) for the dynamical Lie algebra of various quantum circuit families.
Key result (Ragone, Larocca, Cerezo et al., Nature Comms 2024):
  - dim(g) = poly(n) => trainable (no barren plateau)
  - dim(g) = exp(n)  => barren plateau (concentrated gradients)

For each circuit family we generate the matrix Lie algebra from the
generators {iH_k} and close under Lie brackets [A,B] = AB - BA.
"""

import numpy as np


def kron_identity(mat, qubit_idx, n_qubits):
    """Place a single-qubit matrix at position qubit_idx in n_qubits system."""
    ops = [np.eye(2)] * n_qubits
    ops[qubit_idx] = mat
    result = ops[0]
    for op in ops[1:]:
        result = np.kron(result, op)
    return result


def kron_two_qubit(mat, q1, q2, n_qubits):
    """Place a two-qubit gate acting on qubits q1, q2 in n_qubits system.
    mat is 4x4, acts on the subspace of qubits q1 and q2."""
    d = 2 ** n_qubits
    result = np.zeros((d, d), dtype=complex)
    for i in range(d):
        for j in range(d):
            bits_i = [(i >> (n_qubits - 1 - k)) & 1 for k in range(n_qubits)]
            bits_j = [(j >> (n_qubits - 1 - k)) & 1 for k in range(n_qubits)]
            match = all(bits_i[k] == bits_j[k] for k in range(n_qubits)
                        if k != q1 and k != q2)
            if match:
                i_sub = bits_i[q1] * 2 + bits_i[q2]
                j_sub = bits_j[q1] * 2 + bits_j[q2]
                result[i, j] = mat[i_sub, j_sub]
    return result


def lie_algebra_dimension(generators, tol=1e-10, max_iter=50):
    """
    Compute dimension of Lie algebra generated by a set of matrices.

    Uses an efficient approach: maintain an orthonormal basis of the algebra,
    compute brackets only between new elements and existing basis,
    use QR-based projection for linear independence.
    """
    d = generators[0].shape[0]
    d2 = d * d  # max possible dimension

    # Flatten and build initial basis using SVD
    vecs = []
    for g in generators:
        v = g.flatten()
        if np.linalg.norm(v) < tol:
            continue
        # Project out existing basis
        for bv in vecs:
            v = v - np.vdot(bv, v) * bv
        nrm = np.linalg.norm(v)
        if nrm > tol:
            vecs.append(v / nrm)

    # Keep track of which basis elements are new in this round
    old_count = 0
    new_count = len(vecs)

    # Store actual matrices for computing brackets
    basis_mats = []
    for g in generators:
        v = g.flatten()
        for bv in vecs[:len(basis_mats)]:
            pass
        basis_mats.append(g.copy())

    # Rebuild: store basis matrices properly
    basis_mats = []
    for i, g in enumerate(generators):
        if i < new_count:
            # Reconstruct from orthonormal vector
            basis_mats.append(vecs[i].reshape(d, d))

    for iteration in range(max_iter):
        if new_count == old_count:
            break
        if new_count >= d2:
            break

        added_any = False
        # Only compute brackets between new elements and all existing elements
        new_indices = list(range(old_count, new_count))
        all_indices = list(range(new_count))

        pairs_to_try = []
        for i in new_indices:
            for j in all_indices:
                if i != j:
                    pairs_to_try.append((i, j))

        old_count = new_count

        for (i, j) in pairs_to_try:
            if new_count >= d2:
                break
            Mi = vecs[i].reshape(d, d)
            Mj = vecs[j].reshape(d, d)
            bracket = Mi @ Mj - Mj @ Mi
            v = bracket.flatten()

            # Project out existing basis (Gram-Schmidt)
            for bv in vecs:
                v = v - np.vdot(bv, v) * bv
            nrm = np.linalg.norm(v)
            if nrm > tol:
                vecs.append(v / nrm)
                new_count += 1
                added_any = True

        if not added_any:
            break

    return len(vecs)


# Pauli matrices
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)

# Ry generator: i * sigma_y (anti-Hermitian, generator of Ry rotations)
Ry_gen = 1j * sigma_y

# CZ interaction generator: i * |11><11| (generates the CZ phase)
proj_11 = np.zeros((4, 4), dtype=complex)
proj_11[3, 3] = 1.0
CZ_gen = 1j * proj_11


print("=" * 70)
print("Lie Algebra Dimension as Order Parameter for Trainability")
print("Ragone, Larocca, Cerezo et al., Nature Comms 2024")
print("=" * 70)
print()

results = []

for n in [2, 3, 4]:
    d = 2 ** n
    print(f"--- n = {n} qubits, d = {d} ---")

    # 1. Full U(d): dim(u(d)) = d^2
    dim_full = d * d
    print(f"  Full U({d}):        dim(g) = {dim_full} (= d^2)")

    # 2. Product rotations only (Ry on each qubit, no entangling)
    generators_product = []
    for q in range(n):
        generators_product.append(kron_identity(Ry_gen, q, n))

    dim_product = lie_algebra_dimension(generators_product)
    print(f"  Product Ry only:   dim(g) = {dim_product} (expected: n = {n})")

    # 3. Ry + CZ circuit (our test circuit)
    generators_ry_cz = []
    for q in range(n):
        generators_ry_cz.append(kron_identity(Ry_gen, q, n))
    for q in range(n - 1):
        gen = kron_two_qubit(CZ_gen, q, q + 1, n)
        generators_ry_cz.append(gen)

    dim_ry_cz = lie_algebra_dimension(generators_ry_cz)
    print(f"  Ry + CZ (linear):  dim(g) = {dim_ry_cz}")

    results.append((n, d, dim_full, dim_product, dim_ry_cz))
    print()

# Summary table
print("=" * 70)
print("SUMMARY TABLE")
print("=" * 70)
print(f"{'n':>3} {'d':>4} {'Full U(d)':>12} {'Product Ry':>12} {'Ry+CZ':>12}")
print(f"{'':>3} {'':>4} {'dim=d^2':>12} {'dim=n':>12} {'dim':>12}")
print("-" * 50)
for n, d, dim_full, dim_product, dim_ry_cz in results:
    print(f"{n:>3} {d:>4} {dim_full:>12} {dim_product:>12} {dim_ry_cz:>12}")

print()
print("TRAINABILITY PREDICTIONS:")
print("-" * 50)
for n, d, dim_full, dim_product, dim_ry_cz in results:
    print(f"  n={n}: Full U({d}): dim={dim_full} ~ 4^{n} => BARREN PLATEAU")
    if dim_ry_cz == dim_full:
        label = "BARREN PLATEAU"
    elif dim_ry_cz <= n * n * n:
        label = "TRAINABLE (poly)"
    else:
        label = f"INTERMEDIATE (dim/d^2 = {dim_ry_cz/dim_full:.3f})"
    print(f"  n={n}: Ry+CZ:      dim={dim_ry_cz} => {label}")
    print(f"  n={n}: Product:     dim={dim_product} = {n} => TRAINABLE (poly)")
    print()

print("KEY INSIGHT: Product rotations have dim(g)=n (trivially trainable).")
print("Full U(d) has dim(g)=d^2=4^n (barren plateau).")
print("Ry+CZ is intermediate: its Lie algebra dimension determines trainability.")
print()
print("This justifies axiom poly_lie_trainable in LieAlgebraDim.lean:")
print("  dim(g) <= poly(n) => Var[dL/dtheta] >= 1/poly(dim(g))")
